name: proxy-tuning
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - bzip2=1.0.8=h4bc722e_7
  - ca-certificates=2025.1.31=hbcca054_0
  - ld_impl_linux-64=2.43=h712a8e2_2
  - libffi=3.4.6=h2dba641_0
  - libgcc=14.2.0=h77fa898_1
  - libgcc-ng=14.2.0=h69a702a_1
  - libgomp=14.2.0=h77fa898_1
  - liblzma=5.6.4=hb9d3cd8_0
  - libnsl=2.0.1=hd590300_0
  - libsqlite=3.49.1=hee588c1_1
  - libuuid=2.38.1=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.3.1=hb9d3cd8_2
  - ncurses=6.5=h2d0b736_3
  - openssl=3.4.1=h7b32b05_0
  - pip=25.0.1=pyh8b19718_0
  - python=3.9.21=h9c0c6dc_1_cpython
  - readline=8.2=h8228510_1
  - setuptools=75.8.0=pyhff2d567_0
  - tk=8.6.13=noxft_h4845f30_101
  - wheel=0.45.1=pyhd8ed1ab_1
  - pip:
    - absl-py==2.1.0
    - accelerate==1.5.2
    - alpaca-eval==0.1.2
    - annotated-types==0.7.0
    - anyio==4.8.0
    - argon2-cffi==23.1.0
    - argon2-cffi-bindings==21.2.0
    - arrow==1.3.0
    - asttokens==3.0.0
    - async-lru==2.0.4
    - attrs==25.1.0
    - auto-gptq==0.6.0
    - babel==2.17.0
    - beautifulsoup4==4.13.3
    - bleach==6.2.0
    - blinker==1.9.0
    - certifi==2025.1.31
    - cffi==1.17.1
    - charset-normalizer==3.4.1
    - click==8.1.8
    - cmake==3.31.4
    - comm==0.2.2
    - contourpy==1.3.0
    - cycler==0.12.1
    - datasets==2.14.7
    - debugpy==1.8.12
    - decorator==5.1.1
    - deepspeed==0.16.3
    - defusedxml==0.7.1
    - docker-pycreds==0.4.0
    - einops==0.8.1
    - et-xmlfile==2.0.0
    - eval-type-backport==0.2.2
    - exceptiongroup==1.2.2
    - executing==2.2.0
    - fastapi==0.115.8
    - fastjsonschema==2.21.1
    - filelock==3.17.0
    - flask==3.1.0
    - fonttools==4.56.0
    - fqdn==1.5.1
    - fschat==0.2.36
    - gekko==1.2.1
    - gitdb==4.0.12
    - gitpython==3.1.44
    - gradio==4.8.0
    - gradio-client==0.7.1
    - grpcio==1.70.0
    - hjson==3.1.0
    - huggingface-hub==0.29.3
    - idna==3.10
    - importlib-metadata==8.6.1
    - importlib-resources==6.5.2
    - ipykernel==6.29.5
    - ipython==8.18.1
    - isoduration==20.11.0
    - itsdangerous==2.2.0
    - jedi==0.19.2
    - jinja2==3.1.5
    - joblib==1.4.2
    - json5==0.10.0
    - jsonlines==4.0.0
    - jsonpointer==3.0.0
    - jsonschema==4.23.0
    - jsonschema-specifications==2024.10.1
    - jupyter-client==8.6.3
    - jupyter-core==5.7.2
    - jupyter-events==0.12.0
    - jupyter-lsp==2.2.5
    - jupyter-server==2.15.0
    - jupyter-server-terminals==0.5.3
    - jupyterlab==4.3.5
    - jupyterlab-pygments==0.3.0
    - jupyterlab-server==2.27.3
    - kiwisolver==1.4.7
    - latex2mathml==3.77.0
    - lit==18.1.8
    - markdown==3.7
    - markdown2==2.5.3
    - markupsafe==2.1.5
    - matplotlib==3.9.4
    - matplotlib-inline==0.1.7
    - mistune==3.1.2
    - mpmath==1.3.0
    - msgpack==1.1.0
    - nbclient==0.10.2
    - nbconvert==7.16.6
    - nbformat==5.10.4
    - nest-asyncio==1.6.0
    - networkx==3.2.1
    - nh3==0.2.20
    - ninja==1.11.1.3
    - nltk==3.9.1
    - notebook==7.3.2
    - notebook-shim==0.2.4
    - numpy==1.26.4
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cublas-cu12==12.4.5.8
    - nvidia-cuda-cupti-cu11==11.7.101
    - nvidia-cuda-cupti-cu12==12.4.127
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-nvrtc-cu12==12.4.127
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cuda-runtime-cu12==12.4.127
    - nvidia-cudnn-cu11==8.5.0.96
    - nvidia-cudnn-cu12==9.1.0.70
    - nvidia-cufft-cu11==10.9.0.58
    - nvidia-cufft-cu12==11.2.1.3
    - nvidia-curand-cu11==10.2.10.91
    - nvidia-curand-cu12==10.3.5.147
    - nvidia-cusolver-cu11==11.4.0.1
    - nvidia-cusolver-cu12==11.6.1.9
    - nvidia-cusparse-cu11==11.7.4.91
    - nvidia-cusparse-cu12==12.3.1.170
    - nvidia-cusparselt-cu12==0.6.2
    - nvidia-nccl-cu11==2.14.3
    - nvidia-nccl-cu12==2.21.5
    - nvidia-nvjitlink-cu12==12.4.127
    - nvidia-nvtx-cu11==11.7.91
    - nvidia-nvtx-cu12==12.4.127
    - openai==0.28.0
    - openpyxl==3.1.5
    - overrides==7.7.0
    - packaging==24.2
    - pandas==2.2.3
    - pandocfilters==1.5.1
    - parso==0.8.4
    - peft==0.13.2
    - pexpect==4.9.0
    - pillow==10.4.0
    - platformdirs==4.3.6
    - prometheus-client==0.21.1
    - prompt-toolkit==3.0.50
    - psutil==7.0.0
    - ptyprocess==0.7.0
    - pure-eval==0.2.3
    - py-cpuinfo==9.0.0
    - pyarrow==19.0.1
    - pyarrow-hotfix==0.6
    - pycparser==2.22
    - pydantic==2.10.6
    - pydantic-core==2.27.2
    - pylatexenc==2.10
    - pyparsing==3.2.1
    - python-dateutil==2.9.0.post0
    - python-json-logger==3.2.1
    - python-multipart==0.0.20
    - pytz==2025.1
    - pyyaml==6.0.2
    - pyzmq==26.2.1
    - ray==2.42.1
    - referencing==0.36.2
    - requests==2.32.3
    - rfc3339-validator==0.1.4
    - rfc3986-validator==0.1.1
    - rouge==1.0.1
    - rouge-score==0.1.2
    - rpds-py==0.22.3
    - safetensors==0.5.2
    - scipy==1.13.1
    - seaborn==0.13.2
    - send2trash==1.8.3
    - sentry-sdk==2.22.0
    - setproctitle==1.3.4
    - shellingham==1.5.4
    - shortuuid==1.0.13
    - six==1.17.0
    - smmap==5.0.2
    - sniffio==1.3.1
    - soupsieve==2.6
    - stack-data==0.6.3
    - starlette==0.45.3
    - svgwrite==1.4.3
    - sympy==1.13.1
    - tensorboard==2.19.0
    - tensorboard-data-server==0.7.2
    - terminado==0.18.1
    - tinycss2==1.4.0
    - tokenizers==0.21.1
    - tomli==2.2.1
    - tomlkit==0.12.0
    - toolz==1.0.0
    - torch==2.6.0
    - torchaudio==2.6.0+cu126
    - torchvision==0.21.0
    - tornado==6.4.2
    - tqdm==4.67.1
    - traitlets==5.14.3
    - transformers==4.49.0
    - triton==3.2.0
    - typer==0.15.1
    - types-python-dateutil==2.9.0.20241206
    - typing-extensions==4.12.2
    - tzdata==2025.1
    - unidic-lite==1.0.8
    - uri-template==1.3.0
    - urllib3==2.3.0
    - vllm==0.1.2
    - wandb==0.19.6
    - wavedrom==2.0.3.post3
    - wcwidth==0.2.13
    - webcolors==24.11.1
    - webencodings==0.5.1
    - websocket-client==1.8.0
    - werkzeug==3.1.3
    - xformers==0.0.22
    - zipp==3.21.0
